name: Mirror to Company Fork
on:
  push:
    branches: [ main ]   # change this if your default branch is different

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git author
        run: |
          git config user.name "Proactii-Media Mirror Bot"
          git config user.email "hello@proactii.com"

            - name: Push to Proactii-Media/GujaratStore (with token check)
        env:
          COMPANY_TOKEN: ${{ secrets.FORK_PUSH_TOKEN }}
        run: |
          set -euo pipefail

          # sanitize token
          SAFE_TOKEN="$(printf '%s' "$COMPANY_TOKEN" | tr -d '\r\n' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
          echo "SAFE_TOKEN length: ${#SAFE_TOKEN}"

          if [ "${#SAFE_TOKEN}" -lt 20 ]; then
            echo "ERROR: token looks too short. Re-check FORK_PUSH_TOKEN secret."
            exit 2
          fi

          # Quick GitHub API check (will return 200 if token can read the repo)
          HTTP_STATUS="$(curl -s -o /dev/null -w '%{http_code}' \
            -H "Authorization: Bearer $SAFE_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/Proactii-Media/GujaratStore")"

          echo "GitHub API status for repo access: $HTTP_STATUS"

          if [ "$HTTP_STATUS" != "200" ]; then
            echo "ERROR: token cannot access Proactii-Media/GujaratStore (status $HTTP_STATUS)."
            echo " - If status = 401: token invalid or revoked."
            echo " - If status = 404: token lacks permission or repo is private and token can't see it."
            exit 3
          fi

          # remove any existing 'fork' remote
          git remote remove fork || true

          # add remote with sanitized token
          git remote add fork "https://$SAFE_TOKEN@github.com/Proactii-Media/GujaratStore.git"
          git remote -v

          # push current HEAD to fork's main
          git push fork HEAD:main --force-with-lease

          git log --oneline -n 5

