name: Mirror to Company Fork
on:
  push:
    branches: [ main ]   # change this if your default branch is different

permissions:
  contents: write

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git author
        run: |
          git config user.name "Proactii-Media Mirror Bot"
          git config user.email "hello@proactii.com"

      - name: Push to Proactii-Media/GujaratStore
        env:
          COMPANY_TOKEN: ${{ secrets.FORK_PUSH_TOKEN }}
        run: |
          set -euo pipefail

          # ensure no leftover remote
          git remote remove fork || true

          # add remote using token (quote the URL)
          git remote add fork "https://$COMPANY_TOKEN@github.com/Proactii-Media/GujaratStore.git"

          # verify remote
          git remote -v

          # push current HEAD to fork's main (explicit refspec)
          git push fork HEAD:main --force-with-lease

          # print branch status
          git log --oneline -n 5
