name: Sync to Fork

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add fork remote
        run: |
          git remote add fork https://x-access-token:${{ secrets.FORK_PUSH_TOKEN }}@github.com/Proactii-Media/GujaratStore.git
          git remote -v

      - name: Push to fork
        run: |
          git push fork main --force
